[phases.setup]
nixPkgs = ["php83", "php83Packages.composer"]

[phases.install]
cmds = ["composer install --ignore-platform-reqs"]

[phases.build]
cmds = [
  "mkdir -p bootstrap/cache storage/framework/{sessions,views,cache} storage/logs",
  "chmod -R 775 bootstrap/cache storage",
  "composer install --no-dev --optimize-autoloader",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[start]
cmd = "php artisan migrate --force && php artisan db:seed --force --class=DatabaseSeeder && php artisan serve --host=0.0.0.0 --port=$PORT"
